pygments: true
permalink: /:categories/:title
url: http://cnolle.github.com
main_title: Christian Nolle
include: [a, c, j]
description: Young International Worker. Christian Nolle hails from the kingdom of Denmark and currently divides his time between Europe and the Far East. This website contains photographs that span a few decades – some elaborate multi year projects others spur of the moment constellations.
use_tex: true
plugins: ./_plugins
imageurl: http://cnolle.s3.amazonaws.com/cnolle.com/material