permalink: /:title
url: http://cnolle.com
main_title: Christian Nolle
include: [a, c, j]
description: Christian Nolle hails from the kingdom of Denmark. This website contains photographs that span a few decades – some elaborate multi year projects others spur of the moment constellations.
imageurl: http://cnolle.s3.amazonaws.com/cnolle.com/material